version: '3.8'

services:
  production:
    container_name: production_container
    image: compass_production_image
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - FIREBASE_SA=${FIREBASE_SA}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: always
