  version "3.8"

services:
  production:
    container_name: production_container
    image: production_image
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    build:
      context: ./server/
      dockerfile: prod.Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: always
