version: "3.8"

services:
  python_server_ai:
    container_name: python_server_ai_container
    image: python_server_ai_image
    environment:
      - PYTHON_PORT=${PYTHON_PORT}
      - PYTHON_HOST=${PYTHON_HOST}
    build:
      context: ./pythonServer/
    ports:
      - "${PYTHON_PORT}:${PYTHON_PORT}"