name: Python Server Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON_PORT: ${{ secrets.PYTHON_PORT }}
      PYTHON_HOST: ${{ secrets.PYTHON_HOST }}

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
      - name: Install Dependencies
        run: cd pythonServer && pip install -r requirements.txt

      - name: Install Python Coverage Tool
        run: cd pythonServer && pip install pytest-cov

      - name: Run Python Server Tests
        run: cd pythonServer && cd app && pytest --cov-report term-missing --cov=app
