name: Client Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Load .env File Contents
        run: echo "${{ secrets.ENV_FILE }}" > client/.env
      - name: Install Dependencies
        run: cd client && npm install
      - name: Jest Clear Cache
        run: cd client && npx jest --clearCache
      - name: Run Client Tests
        run: cd client && npm run test
      - name: Delete .env File
        run: rm client/.env
        if: always()
